In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree
import pydotplus
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO 
from IPython.display import Image
import graphviz
from sklearn import tree
from os import system
import sklearn
import itertools
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

# Decision Trees

### Đọc dữ liệu

In [2]:
df = pd.read_excel('D:/DATA SCIENCE/TMA/PYTHON/Training/TienGiaTienThat.xlsx', sheetname='Sheet1')

C:\Program Files\Anaconda3\lib\site-packages\pandas\util\_decorators.py:118: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)


### Xem qua dữ liệu

In [3]:
df.groupby('Status').count()

Length  Left  Right  Bottom  Top  Diagonal
Status                                                 
counterfeit     100   100    100     100  100       100
genuine         100   100    100     100  100       100

### Tách nhãn và Thuộc tính riêng

In [4]:
dfLabel = df['Status'].copy()
dfFeatures = df[['Length', 'Left', 'Right', 'Bottom', 'Top', 'Diagonal']]

### Lấy bộ dữ liệu Train và bộ dữ liệu Test

In [5]:

X_train, X_test, y_train, y_test = train_test_split(dfFeatures, dfLabel, test_size=0.25)

### TRAIN mô hình

In [6]:
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(X_train, y_train)

### Đánh giá mô hình trên dữ liệu train

In [7]:
y_pred = clf.predict(X_train)
sklearn.metrics.confusion_matrix(y_train, y_pred, labels=None, sample_weight=None)

array([[74,  0],
       [ 0, 76]], dtype=int64)

### Đánh giá mô hình trên dữ liệu test

In [8]:
y_pred = clf.predict(X_test)
sklearn.metrics.confusion_matrix(y_test, y_pred, labels=None, sample_weight=None)

array([[26,  0],
       [ 1, 23]], dtype=int64)

### Kết thúc Dicision Tress

# Random Forest

### Train mô hình tạo ra 100 cây quyết định

In [9]:
forest = RandomForestClassifier(n_estimators = 100)
forest.fit(X_train, y_train)

#print("#Errors: %i" % np.sum(y != forest.predict(X_train)))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

### Đánh giá mô hình trên dữ liệu train

In [10]:
y_pred = forest.predict(X_train)
sklearn.metrics.confusion_matrix(y_train, y_pred, labels=None, sample_weight=None)

array([[74,  0],
       [ 0, 76]], dtype=int64)

### Đánh giá mô hình trên dữ liệu test

In [11]:
y_pred = forest.predict(X_test)
sklearn.metrics.confusion_matrix(y_test, y_pred, labels=None, sample_weight=None)

array([[26,  0],
       [ 0, 24]], dtype=int64)

# Kết thúc